<h2>Add Product</h2>
<?php if($this->error):?>
<p> There were one or more isues with your submission. Please correct them as 
    indicated below.</p>
<?php endif?> 

<?php 
$form = $this->form;
$form->prepare();
$form->setAttribute('action',$this->url(Null,array('controller'=>'Storeadmin','action'=>'processupload')));
$form->setAttribute('method','post');
echo $this->form()->openTag($form);
?>

<table>
    <tr>
        <td><?php echo $this->formlabel($form->get('name'));?></td>
        <td><?php echo $this->formelement($form->get('name'))?>
            <?php echo $this->formelementerrors($form->get('name'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formlabel($form->get('image'));?></td>
        <td><?php echo $this->formelement($form->get('image'))?>
            <?php echo $this->formelementerrors($form->get('image'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formlabel($form->get('desc'));?></td>
        <td><?php echo $this->formelement($form->get('desc'))?>
            <?php echo $this->formelementerrors($form->get('desc'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formlabel($form->get('cost'));?></td>
        <td><?php echo $this->formelement($form->get('cost'))?>
            <?php echo $this->formelementerrors($form->get('cost'))?></td>
    </tr>
    <tr>
        <td><?php echo $this->formelement($form->get('submit'))?>
            <?php echo $this->formelementerrors($form->get('submit'))?></td>
    </tr>

</table>

<?php echo $this->form()->closeTag();?>