<div>       
<div class="grammarTypeDiv">
            <?php
            echo $this->formlabel($form->get('grammarType'));
            echo $this->formelement($form->get('grammarType'));
            echo $this->formelementerrors($form->get('grammarType'));
            ?>
</div>              
<div class="grammarTypeDiv">
            <?php
            echo $this->formlabel($form->get('grammarType2'));
            echo $this->formelement($form->get('grammarType2'));
            echo $this->formelementerrors($form->get('grammarType2'));
            ?>
</div>              
<div class="grammarTypeDiv">
            <?php
            echo $this->formlabel($form->get('grammarType3'));
            echo $this->formelement($form->get('grammarType3'));
            echo $this->formelementerrors($form->get('grammarType3'));
            ?>
</div>              
</div>                 
            
            