<div>       
<div class="knowledgeTypeDiv">
            <?php
            echo $this->formlabel($form->get('knowledgeType'));
            echo $this->formelement($form->get('knowledgeType'));
            echo $this->formelementerrors($form->get('knowledgeType'));
            ?>
</div>              
<div class="knowledgeTypeDiv">
            <?php
            echo $this->formlabel($form->get('knowledgeType2nd'));
            echo $this->formelement($form->get('knowledgeType2nd'));
            echo $this->formelementerrors($form->get('knowledgeType2nd'));
            ?>
</div>              
<div class="knowledgeTypeDiv">
            <?php
            echo $this->formlabel($form->get('knowledgeType3rd'));
            echo $this->formelement($form->get('knowledgeType3rd'));
            echo $this->formelementerrors($form->get('knowledgeType3rd'));
            ?>
</div>              
</div>                 
            
            