 <? $this->headScript()->appendFile($this->basePath() . '/js/testPaper-analysis.js','text/javascript');?>
<div id="testContent">

	<table class="table">
		<tr class="testpapertr">
			<th width="15%">题号</th>
			<th width="15%">类型</th>
			<th width="20%">Grammar</th>
			<th width="20%">所属知识点</th>
			<th width="10%">错误数</th>
			<th width="20%">操作</th>
		</tr>
<?php foreach ($this->analysisArray as $analysis):?>
<tr>
			<td width="15%"><?php echo $analysis['questionNum'];?></td>
			<td width="15%"></td>
			<td width="20%"><?php echo $analysis['knowledge'];?></td>
			<td width="20%"><?php echo $analysis['knowledge_cn'];?></td>
			<td width="10%"><?php echo $analysis['total'];?></td>
			<td width="20%"><a title='showStudents' >显示相关学生</a></td>

</tr>
<tr class="subTr">
          <td class = 'afterTrTd' colspan=7>
          <input type = 'hidden' name ='totalUser' value ='<?php echo $analysis['totalUser']?>'>
          <div id ='studentList'></div>
            </td>
 </tr>
<?php endforeach;?>
</table>
</div>
<div id="teacherBar">
<a>
<?php 
echo "loginInfo</br>";
echo  "ID：" .$this->identity->id."</br>";
echo  "name：" .$this->identity->name."</br>";
echo  "Role：" .$this->identity->role."</br>";
?>
</a>
</div>
