
<div id="testContent">
<?php foreach($this->testPaperArray as $Testpaper):?>

    <div class = "classSquare"  >
    <a href="<?php echo $this->url('Question',array(
                                                    'action'=>'submit',
                                                    'tid'=>$Testpaper['tid'],
//                                                     'cid'=>$Testpaper['cid'],
                                                    ));?>">   
        <?echo $Testpaper['year'];?>年
         第<?echo $Testpaper['termNum'];?>学期</br>
         第：<?echo $Testpaper['unitNum'];?>单元</br>
    
    </a>
     </div>
    
<?php endforeach;?>
 </div>

<div id="teacherBar">
<a>
<?php 
echo "loginInfo</br>";
echo  "ID：" .$this->identity->id."</br>";
echo  "name：" .$this->identity->name."</br>";
echo  "Role：" .$this->identity->role."</br>";
echo  "classId：" .$this->identity->cid."</br>";
?>
</a>
</div>