
<div id="testContent">
<?php foreach($this->TestPapers as $Testpaper):?>

    <div class = "classSquare"  >
    <a href="<?php echo $this->url('Question',array('action'=>'analysis','id'=>$Testpaper->id));?>">    
     <?echo $Testpaper->year;?>年
              第<?echo $Testpaper->termNum;?>学期</br>
                 第：<?echo $Testpaper->unitNum;?>单元</br>
       试题总数：<?php echo $Testpaper->questionAmount?>           
                  </a>
     </div>
    
<?php endforeach;?>
</div> 

<div id="teacherBar">
<a>
<?php 
echo "loginInfo</br>";
echo  "ID：" .$this->identity->id."</br>";
echo  "name：" .$this->identity->name."</br>";
echo  "Role：" .$this->identity->role."</br>";
echo  "classId：" .$this->identity->cid."</br>";
?>
</a>
</div>