
<h3>增加學生</h3>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(Null, array(
    
    'controller' => 'Student',
    'action' => 'add',
)));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<div id="addClassForm">
	<dl class='zend_form'>

		<div id="formApart1">
			<dt><?php echo $this->formlabel($form->get('name'));?></dt>
			<dd>
        <?php
        echo $this->formelement($form->get('name'));
        echo $this->formelementerrors($form->get('name'));
        ?>
        </dd>
			<dt><?php echo $this->formlabel($form->get('studentNum'));?></dt>
			<dd>
        <?php
        echo $this->formelement($form->get('studentNum'));
        echo $this->formelementerrors($form->get('studentNum'));
        ?>
        </dd>
        <dt><?php echo $this->formlabel($form->get('class'));?></dt>
			<dd>
        <?php
        echo $this->formelement($form->get('class'));
        echo $this->formelementerrors($form->get('class'));
        ?>
        </dd>
			
		 <dt><?php echo $this->formlabel($form->get('gender'));?></dt>
        <dd>
         <?php
        echo  $this->formelement($form->get('gender'));
        ?>
        </dd>
<?php
        echo $this->formelement($form->get('submit'));?>
		</div>

</div>


</dl>
<?php echo $this->form()->closeTag();?>
</div>
