<?php  $this->headScript()->appendFile($this->basePath() . '/js/selectbox.js','text/javascript');?>
<?php  $this->headScript()->appendFile($this->basePath() . '/js/jquery-ui-1.9.2.custom.min.js','text/javascript');?>

<h3>增加班级</h3>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(Null, array(
    
    'controller' => 'ClassManager',
    'action' => 'add',
)));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<div id="addClassForm">
	<dl class='zend_form'>

		<div id="formApart1">
			<dt><?php echo $this->formlabel($form->get('name'));?></dt>
			<dd>
        <?php
        echo $this->formelement($form->get('name'));
        echo $this->formelementerrors($form->get('name'));
        ?>
        </dd>
        <dt><?php echo $this->formlabel($form->get('classType'));?></dt>
			<dd>
        <?php
        echo $this->formelement($form->get('classType'));
        echo $this->formelementerrors($form->get('classType'));
        ?>
        </dd>
			
		 <dt><?php echo $this->formlabel($form->get('year'));?></dt>
        <dd>
         <?php
        echo  $this->formelement($form->get('year'));
        ?>
        </dd>
<?php
        echo $this->formelement($form->get('submit'));?>
		</div>

</div>


</dl>
<?php echo $this->form()->closeTag();?>
</div>
