
<div id="testContent">
<?php foreach($this->ClassName as $ClassManager):?>

    <div class = "classSquare"  >
    <a href="<?php echo $this->url('ClassManager',array('action'=>'detail','id'=>$ClassManager->id));?>">    
     ClassType：<?echo $ClassManager->class_type;?></br>
     <?echo $ClassManager->year;?>级
     <?echo $ClassManager->name;?></br>
                  学生总数：<?echo $ClassManager->student_amount;?></br>
                  班主任：</br>
                  </a>
     </div>
    
<?php endforeach;?>
</div>