


<script type="text/javascript">

$(function(){
	$('#name,#studentNum').focus(function(){
	var txt_value = $(this).val();
    if(txt_value==this.defaultValue){
	$(this).val("");
}
		});
	$('#name,#studentNum').blur(function(){
	var txt_value = $(this).val();
    if(txt_value==""){
	$(this).val(this.defaultValue);
}
		});
});

</script>



<div id='loginingContent'>
    <div id='welcome'>
    <h4>欢迎来到...（名字还没有想好）</h4>
    slogan...也没有想好
    </div>
	<div id='loginTable'>
            <?php
            $form = $this->form;
            $form->prepare();
            $form->setAttribute('action', $this->url(Null, array(
                'controller' => 'logining',
                'action' => 'process'
            )));
            $form->setAttribute('method', 'post');
            echo $this->form()->openTag($form);
            ?>
            <dl class='zend_form'>
            			<dt><?php echo $this->formlabel($form->get('name'));?></dt>
            			<dd>
            <?php
            echo $this->formelement($form->get('name'));
            echo $this->formelementerrors($form->get('name'));
            ?>
            </dd>
            
            			<dt><?php echo $this->formlabel($form->get('studentNum'));?></dt>
            			<dd id="password">
            <?php
            echo $this->formelement($form->get('studentNum'));
            echo $this->formelementerrors($form->get('studentNum'));
            ?>
            </dd>
            			<dd><?php echo $this->formelement($form->get('submit'));?></dd>
            		</dl>
            <?php echo $this->form()->closeTag();?>
</div>
</div>