<?php echo $this->doctype(); ?>

<html lang="zh-CN">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <?php echo $this->headTitle($this->translate('Communication Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') 
                                    /* ->prependFile($this->basePath() . '/js/login.js','text/javascript') */;
        ?>
       	<!-- Override Styles -->
       <?php echo $this->headStyle(); ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Communication Application') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <!--  <li ><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>  -->
							<li ><a href="<?php echo $this->url('groupchat') ?>"><?php echo $this->translate('Group chat') ?></a></li>                            		                        
							<li ><a href="<?php echo $this->url('usermanager') ?>"><?php echo $this->translate('User') ?></a></li>                            		                        
							<li ><a href="<?php echo $this->url('uploadmanager') ?>"><?php echo $this->translate('Upload') ?></a></li>
							<li ><a href="<?php echo $this->url('Storeadmin', array('action' => 'addproduct')) ?>"><?php echo $this->translate('Add Product  ') ?></a></li>
							<li ><a href="<?php echo $this->url('album/login', array('action' => 'logout')) ?>"><?php echo $this->translate('Logout') ?></a></li>				
							<li ><a href="<?php echo $this->url('TestPaper') ?>"><?php echo $this->translate('试卷') ?></a></li>				
                        </ul>
                    </div><!--/.nav-collapse -->
                    <div class="search"><input type="text" id="inputsearch" class="" value="input the product name" /></div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
           
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
