    <?php echo $this->doctype();
    ?>

<html lang="zh-CN">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <?php echo $this->headTitle($this->translate('Communication Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/login.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') 
                                       ->appendFile($this->basePath() . '/js/testPaper-ui2.js','text/javascript')            
            ->appendFile($this->basePath() . '/js/jquery-ui-1.9.2.custom.min.js','text/javascript') 
        ?>
       	<!-- Override Styles -->
       <?php echo $this->headStyle(); ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('错题集') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <!--  <li ><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>  -->
							<li ><a href="<?php echo $this->url('TestPaper') ?>"><?php echo $this->translate('试卷') ?></a></li>				
							<li ><a href="<?php echo $this->url('Question') ?>"><?php echo $this->translate('答卷') ?></a></li>				
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
           
        </div>
         <div id="sidebar">
            <?php echo $this->sidebar ;?>
         </div>
         <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
