<?php echo $this->doctype(); 
// $this->layout()->panel = $this->render('album/logining/panel');
?>
<html lang="zh-CN">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <?php echo $this->headTitle($this->translate('试卷分析系统'))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

        <!-- Le styles -->  
        <?php
        
echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/images/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
            ->
        prependStylesheet($this->basePath() . '/css/bootstrap.min.css')?>

        <!-- Scripts -->
        <?php
        
echo $this->headScript()
            ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'))
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js') 
            ->appendFile($this->basePath() . '/js/login.js','text/javascript')            
            ->appendFile($this->basePath() . '/js/testPaper-ui.js','text/javascript')            
            ->appendFile($this->basePath() . '/js/jquery-ui-1.9.2.custom.min.js','text/javascript')            
        ?>
       	<!-- Override Styles -->
       <?php echo $this->headStyle(); ?>

    </head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse"
					data-target=".nav-collapse"> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
				</a> <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('改错本') ?></a>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<!--  <li ><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>  -->
						<li><a href="<?php echo $this->url('TestPaper') ?>"><?php echo $this->translate('试卷') ?></a></li>
						<li><a href="<?php echo $this->url('store') ?>"><?php echo $this->translate('商城') ?></a></li>
						<li><a
							href="<?php echo $this->url('TestPaper', array('action' => 'wash')) ?>"><?php echo $this->translate('洗车') ?></a></li>
					</ul>
					
					<?php 
					$this->layout()->panel = $this->render('album/logining/panel');
					
					echo $this->layout()->panel;?>
				</div>
				<!--/.nav-collapse -->
			</div>
		</div>
	</div>
	<div class="container">
		<div id="Catalog">
			<div id="CataInfo">

				<div class="item fore1">
					<span class="testPaperCataInfoSpan">
						<h3>
							<a
								href="<?php echo $this->url('TestPaper',array('action'=>'index'));?>">试题首页</a>
						</h3>

					</span>
				</div>

				<div class="item fore2">
					<span class="testPaperCataInfoSpan">
						<h3>
							<a class="loginWindow"
								href="<?php echo $this->url('TestPaper',array('action'=>'add'));?>">创建试卷</a>
						</h3>
					</span>
					<div class="testPaperSubitem">
						<dd>
							<h3>
								<a
									href="<?php echo $this->url('TestPaper',array('action'=>'QuestionType'));?>">科目目录</a>
							</h3>
							<h3>
								<a
									href="<?php echo $this->url('TestPaper',array('action'=>'createType'));?>">科目试题创建</a>
							</h3>
						</dd>
					</div>
				</div>

				<div class="item fore2">
					<span class="testPaperCataInfoSpan">
						<h3>
							<a
								href="<?php echo $this->url('Knowledge',array('action'=>'index'));?>">知识点管理</a>
						</h3>
					</span>
					<div class="testPaperSubitem">
						<dd>
							<h3>
								<a href="<?php echo $this->url('Knowledge',array('action'=>'add'));?>">知识点创建</a>
							</h3>
							<h3>
								<a href="#">搜索试题</a>
							</h3>
						</dd>
					</div>
				</div>
				<div class="item fore2">
					<span class="testPaperCataInfoSpan">
						<h3>
							<a
								href="<?php echo $this->url('ClassManager',array('action'=>'index'));?>">班级管理</a>
						</h3>
					</span>
					<div class="testPaperSubitem">
						<dd>
							<h3>
								<a
									href="<?php echo $this->url('ClassManager',array('action'=>'add'));?>">班级创建</a>
							</h3>
							<h3>
								<a href="<?php echo $this->url('Student',array('action'=>'add'));?>">新生录入</a>
							</h3>
							<h3>
								<a href="#">xls录入</a>
							</h3>
							<h3>
								<a href="#">个体分析</a>
							</h3>
							<h3>
								<a href="#">整体分析</a>
							</h3>
						</dd>
					</div>
				</div>
				<div class="item fore2">
					<span class="testPaperCataInfoSpan">
						<h3>
							<a
								href="#">学生提交错题</a>
						</h3>
					</span>
					<div class="testPaperSubitem">
						<dd>
							<h3>
								<a
									href="<?php echo $this->url('Question',array('action'=>'index'));?>">查看试卷</a>
							</h3>
						</dd>
					</div>
				</div>
 
			</div>
		</div>
            <?php echo $this->content; ?>
           
        </div>
	<!-- /container -->
        <?php echo $this->inlineScript()?>
    </body>
</html>
