<h3><?php 
$testPaper = $this->testPaper;
echo"学年: &nbsp".$testPaper->year."&nbsp&nbsp";
echo"学期:".$testPaper->termNum."&nbsp&nbsp";
echo "单元:".$testPaper->unitNum;
?></h3>     
增加试卷和编辑试卷有所不同，只有点击了增加试卷，服务器才会写入试卷中的Question
<table class="table">
<tr>
<th>试题号</th>
<th>所属类型</th>
<th>详细</th>
<th>难度</th>
</tr>
<?php

$form=$this->form;
$form->prepare();
$form->setAttribute('action',$this->url(Null,array('controller'=>'TestPaper','action'=>'process')));
$form->setAttribute('method','post');
echo $this->form()->openTag($form);
for ($i=1;$i<$testPaper->questionAmount+1;$i++){
?>

<tr>
<td width="5%">
<?php 
      echo $i;
      echo $this->formelement($form->get('tid')->setAttribute('value',$testPaper->id));
      echo  $this->formelement($form->get('questionNum[]')->setAttribute('value',$i));
                              echo $this->formElementErrors($form->get('questionNum[]'));?></td>
<td width="15%"><?php echo $this->formelement($form->get('grammaType[]'));
                      echo $this->formElementErrors($form->get('grammaType[]')); ?></td>
<td width="40%"><?php echo $this->formelement($form->get('content[]'));
                      echo $this->formElementErrors($form->get('content[]')); ?></td>
<td width="25%"><?php echo $this->formelement($form->get('grade[]'));
                      echo $this->formElementErrors($form->get('grade[]'));?></td></tr><?php }?>
<dd><?php echo $this->formelement($form->get('submit'));?></dd>	
<?php echo $this->form()->closeTag();?>

</table>