<h3>试卷编辑</h3></br>
<h4><?php 
$testPaper = $this->TestPaper;
$Questions = $this->Questions;
$form = $this->form;
echo"学年: &nbsp".$testPaper->year."&nbsp&nbsp";
echo"学期:".$testPaper->termNum."&nbsp&nbsp";
echo "单元:".$testPaper->unitNum;
?>




<a href="<?php echo $this->url('TestPaper',array('action'=>'index'));?>">返回主页</a></h3>
</h4>  
<table class = "table">
   <tr class="testpapertr">  
<th>试题号</th>
<th>所属类型</th>
<th>详细</th>
<th>难度</th>
<th>保存</th>
</tr>


<?php 
foreach ($Questions as $Question){
$form->prepare();

$form->setAttribute('action',$this->url(Null,array('controller'=>'TestPaper','action'=>'editprocess')));
$form->setAttribute('method','post');
echo $this->form()->openTag($form);
?>
<tr>
<td width="10%"><?php echo $Question['questionNum'];
                      echo $this->formelement($form->get('id')->setAttribute('value',$Question['id']));
                      echo $this->formelement($form->get('tid')->setAttribute('value',$Question['tid']));
                      echo $this->formelement($form->get('questionNum[]')->setAttribute('value',$Question['questionNum']));
                      echo $this->formElementErrors($form->get('questionNum[]'));?></td>
<td width="15%"><?php echo $this->formelement($form->get('grammaType[]')->setAttribute('value',$Question['grammaType']));
                      echo $this->formElementErrors($form->get('grammaType[]')); ?></td>
<td width="40%"><?php echo $this->formelement($form->get('content[]')->setAttribute('value',$Question['content']));
                      echo $this->formElementErrors($form->get('content[]')); ?></td>
<td width="25%"><?php echo $this->formelement($form->get('grade[]')->setAttribute('value',$Question['grade']));
                      echo $this->formElementErrors($form->get('grade[]'));?></td>
<td width="10%"><?php echo $this->formelement($form->get('submit'));?></td>	
          
          </tr>
          
<?php echo $this->form()->closeTag(); }
?>
</table>