<h3>试卷编辑</h3></br>
<h4>
    <?php 
        $testPaper = $this->TestPaper;
        $Questions = $this->Questions;
        $form = $this->form;
        $form2 = $this->form2;
        echo"学年: &nbsp".$testPaper->year."&nbsp&nbsp";
        echo"学期:".$testPaper->termNum."&nbsp&nbsp";
        echo "单元:".$testPaper->unitNum;?>
    <a href="<?php echo $this->url('TestPaper',array('action'=>'index'));?>">返回主页</a>
</h4>  
<table class = "table">
   <tr class="testpapertr"> 
        <th>题号</th>
        <th>所属类型/知识点</th>
        <th>难度</th>
        <th>标签</th>
        <th>修改时间</th>
        <th>修改次数</th>
        <th>保存</th>
    </tr>

<?php

$a = $testPaper->questionType;
$b = explode(',', $a); // 分离出题目的格式“题型：起始数-终止数，题型：起始数-终止数”

$count = count($b); // 计算题型总数
for ($i = 0; $i < $count - 1; $i ++) { // 这里要减1，
    list ($type, $num) = explode(":", $b[$i]); // 分离出“题型和起始数-终止数”
    list ($start, $end) = explode("-", $num); // 分离出“起始数和终止数”
    for ($qstart = $start; $qstart <= $end; $qstart ++) {
        
        
                
        echo "<tr class = 'square-" . $i . "'  >" ;
        $form->prepare();
        $form->setAttribute('action',$this->url(Null,array('controller'=>'TestPaper','action'=>'editprocess')));
        $form->setAttribute('method','post');
        echo $this->form()->openTag($form);
        
        echo "<td class='questionNum' width = '5%'>".$Questions[$qstart - 1]['questionNum'];
        echo $this->formelement($form->get('id')->setAttribute('value',$Questions[$qstart - 1]['id']));
        echo $this->formelement($form->get('questionNum2')->setAttribute('value',$Questions[$qstart - 1]['questionNum']));
        echo "<input type ='hidden' name ='knowledge_id' value =".$Questions[$qstart - 1]['knowledge_id']."></td>";
        
        echo "<td class='showType' width = '15%'>".$Questions[$qstart - 1]['knowledgeName']."</br>".$Questions[$qstart - 1]['knowledgeCN_Name']."</td>";
        
        echo "<td width = '10%'>";
        echo "<ul class = 'rating star_".$Questions[$qstart - 1]['grade']."'>
                  <li class= 'star_1'><a href='#' title=1>1</a></li>
                  <li class= 'star_2'><a href='#' title=2>2</a></li>
                  <li class= 'star_3'><a href='#' title=3>3</a></li>
                  <li class= 'star_4'><a href='#' title=4>4</a></li>
                  <li class= 'star_5'><a href='#' title=5>5</a></li>
              </ul>";
        echo"<input type ='hidden' name ='grade' value ='".$Questions[$qstart - 1]['grade']."'></td>";
        echo "<td width = '10%'>";
        echo $this->formelement($form->get('content[]')->setAttribute('value',$Questions[$qstart - 1]['tag']));
        echo $this->formElementErrors($form->get('content[]'))."</td>";
        
     
        echo "<td class ='editTime' width = '10%'> ".$Questions[$qstart - 1]['edit_time']."</td>";
        echo "<td class = 'editCount' width = '10%'> ".$Questions[$qstart - 1]['edit_count']."</td>";
        
        echo "<td width = '10%'>";
        echo "<button id='questionSubmit'>submit</buttno>";
//         echo $this->formelement($form->get('submit')->setAttribute('value','保存'))."</td></tr>";

        echo "<tr class = subTr><td class = 'afterTrTd' colspan=7>";?>
        <div class = "afterTrDiv">
        
       <div id = "navBar">
       <input type="checkbox" name="gradeCheck" /> 取消勾选关闭按年级筛选知识点分类   
       <input type="checkbox" name="questionTypeCheck" /> 取消勾选关闭题型分类支持</br>   
       <input type="text" name="questionTypeSearch" /><button>搜索知识点</button>  
        </div> 
        
        
            <div class="knowledgeTypeDiv">
                        <?php
                        echo $this->formlabel($form2->get('knowledgeType'));
                        echo $this->formelement($form2->get('knowledgeType'));
                        echo $this->formelementerrors($form2->get('knowledgeType'));
                        ?>
            </div>              
            <div class="knowledgeTypeDiv">
                        <?php
                        echo $this->formlabel($form2->get('knowledgeType2nd'));
                        echo $this->formelement($form2->get('knowledgeType2nd'));
                        echo $this->formelementerrors($form2->get('knowledgeType2nd'));
                        ?>
            </div>              
            <div class="knowledgeTypeDiv">
                        <?php
                        echo $this->formlabel($form2->get('knowledgeType3rd'));
                        echo $this->formelement($form2->get('knowledgeType3rd'));
                        echo $this->formelementerrors($form2->get('knowledgeType3rd'));
                        ?>
            </div>              
            <div class="knowledgeTypeDiv">
                        <?php
                        echo $this->formlabel($form2->get('knowledgeType4'));
                        echo $this->formelement($form2->get('knowledgeType4'));
                        echo $this->formelementerrors($form2->get('knowledgeType4'));
                        ?>
                        <input type="text" name="addKnowledge" id ="addkonwledge"/>
                        <button>增加知识点</button>
            </div>              
        </div>      
        
        <?php 
        echo $this->form()->closeTag();
        echo "</td></tr>";
        
    }
}
?>



</table>