
<div id="testContent">
	<table class="table">
		<tr class="testpapertr">
			<th width="10%">学年</th>
			<th width="10%">学期</th>
			<th width="10%">单元</th>
			<th width="10%">题数</th>
			<th width="10%">创建时间</th>
			<th width="10%">答案总数</th>
			<th width="20%">操作</th>
		</tr>
<?php foreach ($this->TestPapers as $TestPaper):?>
<tr>
			<td width="10%"><?php echo $TestPaper->year;?></td>
			<td width="10%"><?php echo $this->escapehtml($TestPaper->termNum);?></td>
			<td width="10%"><?php echo $this->escapehtml($TestPaper->unitNum);?></td>
			<td width="10%"><?php echo $this->escapehtml($TestPaper->questionAmount);?></td>
			<td width="10%"><?php echo date('Y-m-d',$this->escapehtml($TestPaper->createtime));?></td>
			<td width="10%"></td>

			<td width="20%">
<?php if($TestPaper->created == 0){?>
<a
				href="<?php echo $this->url('TestPaper',array('action'=>'create','id'=>$TestPaper->id));?>">创建</a>&nbsp<?php }?>
<a
				href="<?php echo $this->url('TestPaper',array('action'=>'edit','id'=>$TestPaper->id));?>">编辑</a>
				<a
				href="<?php echo $this->url('TestPaper',array('action'=>'delete','id'=>$TestPaper->id));?>">删除</a>
			</td>
		</tr>
<?php endforeach;?>
</table>
</div>