<?php  $this->headScript()->appendFile($this->basePath() . '/js/test.js','text/javascript');?>
<?php  $this->headScript()->appendFile($this->basePath() . '/js/move.js','text/javascript');?>
<?php  $this->headScript()->appendFile($this->basePath() . '/js/jquery.ui.sortable.js','text/javascript');?>
<?php  $this->headScript()->appendFile($this->basePath() . '/js/jquery.ui.core.js','text/javascript');?>
<?php  $this->headScript()->appendFile($this->basePath() . '/js/jquery.ui.mouse.js','text/javascript');?>
<?php  $this->headScript()->appendFile($this->basePath() . '/js/jquery.ui.widget.js','text/javascript');?>
<?php  $this->headScript()->appendFile($this->basePath() . '/js/jquery.js','text/javascript');?>
<a href="#" class="modalShow">show modal</a> 


<div id ="button">Button </div>
<div id ="type11">11111111</div>
<!-- <style type="text/css"> -->
/* #module_list{margin-left:4px}  */
/* .modules{float:left; width:200px; height:140px; margin:10px; border:1px solid #acc6e9;  */
/*  background:#e8f5fe}  */
/* .m_title{height:24px; line-height:24px; background:#afc6e9}  */
/* #loader{height:24px; text-align:center}  */
<!-- </style> -->

<!-- <div id="loader"></div>  -->
<!-- <div id="module_list">  -->
<!--    <input type="hidden" id="orderlist" />  -->
<!--    <div class="modules" title="1">  -->
<!--       <h3 class="m_title">Module:1</h3>  -->
<!--       <p>1</p>  -->
<!--    </div>  -->
<!--   <div class="modules" title="2">  -->
<!--       <h3 class="m_title">Module:2</h3>  -->
<!--       <p>2</p>  -->
<!--    </div> <div class="modules" title="3">  -->
<!--       <h3 class="m_title">Module:3</h3>  -->
<!--       <p>3</p>  -->
<!--    </div> <div class="modules" title="4">  -->
<!--       <h3 class="m_title">Module:4</h3>  -->
<!--       <p>4</p>  -->
<!--    </div>  -->
<!-- </div>  -->






	<title>jQuery UI Sortable</title>
	<style type="text/css">
		#myList{
			width: 80px;
			background: #EEE;
			padding: 5px;
			list-style: none;
		}
		#myList a{
			text-decoration: none;
			color: #0077B0;
		}
		#myList a:hover{
			text-decoration: underline;
		}
		#myList .qlink{
			font-size: 12px;
			color: #666;
			margin-left: 10px;
		}
	</style>
</head>
<body>
<ul id="myList">
	<li><a href="#">心情</a></li>
	<li>
		<a href="#">相册</a>
		<a href="#" class="qlink">上传</a>
	</li>
	<li>
		<a href="#">日志</a>
		<a href="#" class="qlink">发表</a>
	</li>
	<li><a href="#">投票</a></li>
	<li><a href="#">分享</a></li>
	<li><a href="#">群组</a></li>
</ul>

<script type="text/javascript" src="../../scripts/jquery.js"></script>
<script type="text/javascript" src="js/jquery.ui.core.js"></script>
<script type="text/javascript" src="js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="js/jquery.ui.mouse.js"></script>
<script type="text/javascript" src="js/jquery.ui.sortable.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$("#myList").sortable(); //直接让myList下的元素可以拖动排序
});
</script>


















