<h3>【LOGO】南京预约上门洗车&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp我的服务&nbsp&nbsp|&nbsp&nbsp积分&nbsp&nbsp|&nbsp&nbsp汽车生活管理</h3></br>

<h5>&nbsp&nbsp&nbsp晴&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp阴&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp雨&nbsp&nbsp&nbsp数据来源：中国天气 year：month：day：hour</h5>
<button>因天气原因免责申明</button></br></br>


<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(Null, array(
    
    'controller' => 'ClassManager',
    'action' => 'add',
)));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<div id="testPaperForm">
	<dl class='zend_form'>

		<div id="formApart1">
			<dt><?php echo $this->formlabel($form->get('name'));?></dt>
			<dd>
        <?php
        echo $this->formelement($form->get('name'));
        echo $this->formelementerrors($form->get('name'));
        ?>
        </dd>
			<dt><?php echo $this->formlabel($form->get('carNum'));?></dt>
			<dd>
        <?php
        echo $this->formelement($form->get('carNum'));
        echo $this->formelementerrors($form->get('carNum'));
        ?>
        </dd>
			<dt><?php echo $this->formlabel($form->get('address'));?></dt>
			<dd>
        <?php
        echo $this->formelement($form->get('address'));
        echo $this->formelementerrors($form->get('address'));
        ?>
        </dd>
        <dt><?php echo $this->formlabel($form->get('classType'));?></dt>
			<dd>
        <?php
        echo $this->formelement($form->get('classType'));
        echo $this->formelementerrors($form->get('classType'));
        ?>
        </dd>
			
		 <dt><?php echo $this->formlabel($form->get('time'));?></dt>
        
        <dd>
         <?php
        echo  $this->formelement($form->get('time'));
       
        ?>
        </dd>
<?php
        echo $this->formelement($form->get('submit'));?>
		</div>

</div>


</dl>
<?php echo $this->form()->closeTag();?>
</div>