
<section class="login-confirm">
<h2>FileUpload Manager</h2>
<p> Welcome! <?php echo $this->user_email; ?> 
<?php echo $this->user_id; ?></p>
</section>
<table class="table">
<tr>
<th>Filename</th>
<th>Label</th>
<th>Actions</th>
</tr>
<?php foreach ($this->myupload as $myUploads):?>
<Tr>
<Td><?php echo $this->escapehtml($myUploads->filename);?></Td>
<Td><?php echo $this->escapehtml($myUploads->label);?></Td>
<td><A href="<?php echo $this->url('uploadmanager',array('action'=>'delete','id'=>$myUploads->id));?>">delete</A>|<A href="<?php echo $this->url('uploadmanager',array('action'=>'edit','id'=>$myUploads->id));?>">edit</A></td>
</tr>
<?php endforeach;?>
</table>
<h2>Shared Uploads</h2>

<table class="table">
<tr>
    <th>Label</th>
    <th>Download</th>
    <th>Shared By</th> 
</tr>
<?php foreach ($sharedUploadsList as $uploadId => $upload) : ?>
<tr>
    <td><?php echo $this->escapeHtml($upload['label']);?></td>
    <td><a href="<?php echo $this->escapeHtml($this->url(null,
            array('controller' => 'uploadmanager','action'=>'fileDownload', 'id' => $uploadId)));?>">Download</a> </td>
    <td><?php echo $this->escapeHtml($upload['owner']);?></td>    
</tr>
<?php endforeach; ?>
</table>
<td><A href="<?php echo $this->url('uploadmanager',array('action'=>'upload',));?>">New File Upload  </A></td>