
<h2>Upload Login Form</h2>
<?php 
$form=$this->form;
$form->prepare();
$form->setAttribute('action',$this->url(Null,array('controller'=>'Uploadmanager','action'=>'process')));
$form->setAttribute('method','post');
echo $this->form()->openTag($form);?>
<dl class='zend_form'>
<dt><?php echo $this->formlabel($form->get('email'));?></dt>
<dd>
<?php 
          echo $this->formelement($form->get('email'));
          echo $this->formelementerrors($form->get('email'));?>
</dd>

<dt><?php echo $this->formlabel($form->get('password'));?></dt>
<dd>
<?php 
          echo $this->formelement($form->get('password'));
          echo $this->formelementerrors($form->get('password'));?>
</dd>
<dd><?php echo $this->formelement($form->get('submit'));?></dd>
</dl>
<?php echo $this->form()->closeTag();?>